# Numpy vs list

In [52]:
import numpy as np
import sys
import time
a = np.array([1,2,3])
a

array([1, 2, 3])

# This shows the space used by list :-

In [53]:
l = range(1000)
print(sys.getsizeof(5) * len(l))

28000


# This shows the space used by numpy :-

In [54]:
array = np.arange(1000)
print(array.size * array.itemsize)

4000


In [55]:
SIZE = 1000000

l1 = range(SIZE)
l2 = range(SIZE)

a1 = np.arange(SIZE)
a2 = np.arange(SIZE)

# This shows time used by list :-

In [65]:
start = time.time()
result = [(x + y) for x, y in zip(l1, l2)]
print("python list took: ", (time.time() - start) * 1000, "ms")

python list took:  99.64585304260254 ms


# This shows time used in numpy for array :-

In [66]:
start = time.time()
result = a1 + a2
print("python numpy took: ", (time.time() - start) * 1000, "ms")

python numpy took:  7.9193115234375 ms


# Some basic calculation in numpy :-

In [58]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
result = a1 + a2
result

array([5, 7, 9])

In [59]:
result = a2 - a1
result

array([3, 3, 3])

In [60]:
result = a1 * a2
result

array([ 4, 10, 18])

In [67]:
result = a1 / a2
result

array([0.25, 0.4 , 0.5 ])